
namespace jshepler.ngu.mods
{
    internal enum Menu
    {
        BasicTraining = 0,
        // 1 and 2 don't seem to be anything, at least anything useful to players
        Adventure = 3,
        Inventory = 4,
        Augments = 5,
        BloodMagic_Rituals = 6,
        BloodMagic_Spells = 7,
        NGU_Energy = 8,
        Yggdrasil = 9,
        Stats_Misc = 10,
        Settings_Page1 = 11,
        Challenges = 12,
        EXP_Energy = 13,
        Wandoos = 14,
        FightBoss = 15,
        MoneyPit = 16,
        AdvancedTraining = 17,
        TimeMachine = 18,
        Shop_Shop1_Boosts1 = 19,
        ItemList = 20,
        Learn_WTF = 21,
        TooltipLog = 22,
        Rebirth = 23,
        Bestiary = 24,
        Shop_Shop2_Special1 = 25,
        Info_nStuff = 26,
        Shop_Kreds1_BuyAP = 27,
        Shop_Shop3_Items = 28,
        Shop_Shop4_EXP_PP = 29,
        Achievements = 30,
        Shop_Shop5_Special2 = 31,
        EXP_Magic = 32,
        EXP_AdventureStats = 33,
        EXP_AdventureSpecial = 34,
        EXP_Misc = 35,
        DailySpin = 36,
        NGU_Magic = 37,
        EXP_Yggdrasil = 38,
        Beards = 39,
        Settings_Page2 = 40,
        Perks = 41,
        Shop_Shop6_Boosts2 = 42,
        StatBreakdowns = 43,
        GoldDiggers = 44,
        SpecialPrize = 45,
        Shop_Kreds2_SpecialPacks = 46,
        ItopodNamesList = 47,
        Quests = 48,
        Quirks = 49,
        Shop_Shop7_Special3 = 50,
        EXP_R3 = 51,
        Hacks = 52,
        Wishes = 53,
        Krissmuss = 54,
        Cards = 55,
        Shop_Shop8_Special4 = 56,
        Cooking = 57,
    }
}
